name: ci-golang-workflow
on: [push]
jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
    # action is a git repo: github.com/action/
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run src/math.go